### ISSUE TITLE
Please update this awesome tutorial

### ISSUE THREAD

**Issue by mnlbox** [dorgamit/rocketchat#1]
Hi @diegodorgam ,
I see your tutorial and it's very useful. I have some suggestion and request for this:
* Please update your tutorial to latest RC version.
* Please add more configuration option. For example with Docker, ...
* Add section about how we can use Let's Encrypt SSL certificate with my RC.
* Add a section about how create custom Docker image from my RC when we use custom version of RC. (How to deploy customized and unofficial version of RC from code)
* Add a section about how we can a mix HA deploy with Docker, Kubernetes, ...
* Add some automation script for backup MongoDB database and uploaded files somewhere in Google Drive, DropBox or an simple FTP server.

**Comment by diegodorgam** [comment]
thanks @mnlbox =) 
I really need to do this, in the mean time, there is a lot of useful stuff in https://rocket.chat/docs/installation/ you can checkout some of those, they're all in github too.
I've been meaning to work on those repos instead of this, just it make it more official.

**Comment by mnlbox** [comment]
@diegodorgam Can you tell me your username in: https://open.rocket.chat
I want ask some question there and have some suggestion. :wink:

**Comment by mnlbox** [comment]
@diegodorgam

**Comment by diegodorgam** [comment]
Hi,
in open.rocket.chat I'm under the user diego.dorgam.
in most social networks also, some with the dot, some without =)
